### ISSUE TITLE
Implementation Concerns

### ISSUE THREAD

**Issue by mattjohnsonpint** [markitondemand/moment-msdate#1]
I'm ok with the idea of a moment plugin for OADates, but I have a few concerns:
- I would expect the external API to be `moment.fromOADate(x)`, not `moment().fromOADate(x)`.  By attaching it to the moment instance, you're first creating a "now" moment, then throwing it away.
- The function clearly returns a moment, otherwise it wouldn't be in here at all.  So in the docs, I wouldn't show passing the result out as a `jsDate` and back into the moment constructor again.
- You might want to mention that an OADate is "unspecified", and therefore based on the local time zone by default.  You might also want a clear way to pass in an OADate that is based on UTC.
- In the implementation itself, you appear to be taking the timezone from a UTC-based conversion and then applying it to the input to determine the local time.  In other words `Offset(UTC(OADate)) + UTC(OADate)`.  That's not necessarily going to yield the correct value.  The offset applies at the destination - not at the source.  Instead, you should be starting with a new Date of the OADate base and working from there.
- There are some implementation quirks about negative numbers that are described in the MSDN reference, but you don't appear to be handling them.  You might want to consider the internal .Net implementation code of `DateTime.FromOADate` which is as follows:

``` csharp
// Creates a DateTime from an OLE Automation Date. 
//
public static DateTime FromOADate(double d) { 
    return new DateTime(DoubleDateToTicks(d), DateTimeKind.Unspecified); 
}

// Converts an OLE Date to a tick count. 
// This function is duplicated in COMDateTime.cpp 
internal static long DoubleDateToTicks(double value) {
    if (value >= OADateMaxAsDouble || value <= OADateMinAsDouble) 
        throw new ArgumentException(Environment.GetResourceString("Arg_OleAutDateInvalid"));
    long millis = (long)(value * MillisPerDay + (value >= 0? 0.5: -0.5));
    // The interesting thing here is when you have a value like 12.5 it all positive 12 days and 12 hours from 01/01/1899
    // However if you a value of -12.25 it is minus 12 days but still positive 6 hours, almost as though you meant -11.75 all negative 
    // This line below fixes up the millis in the negative case
    if (millis < 0) { 
        millis -= (millis % MillisPerDay) * 2; 
    }

    millis += DoubleDateOffset / TicksPerMillisecond;

    if (millis < 0 || millis >= MaxMillis) throw new ArgumentException(Environment.GetResourceString("Arg_OleAutDateScale"));
    return millis * TicksPerMillisecond; 
}
```

While it's not going to be identical in JavaScript, your code should follow the same logic.
- You might also want to implement `.toOADate()`
- Unit Tests?

**Comment by markhealey** [comment]
Couple updates with `996ff8a` and `212ea8d`:
- [x] I would expect the external API to be `moment.fromOADate(x)`
- [x] So in the docs, I wouldn't show passing the result out as a `jsDate` and back into the moment constructor again.
- [x] You might want to mention that an OADate is "unspecified"
- [ ] The offset applies at the destination - not at the source. Instead, you should be starting with a new Date of the OADate base and working from there.
- [x] You might also want to implement .toOADate()
- [ ] There are some implementation quirks about negative numbers that are described in the MSDN reference, but you don't appear to be handling them.
- [x] Unit Tests? _I added [six tests](http://markitondemand.github.io/moment-msdate/) with more we can add in time_

**Comment by markhealey** [comment]
Also added a new landing page for this with the tests and functioning examples:

http://markitondemand.github.io/moment-msdate/

**Comment by mattjohnsonpint** [comment]
Looking better.  Keep up the good work.  I'll take another look when you can address the final two points.

I'm curious though - what is the use case for needing this plugin?  I mean, I know all about OADates, it's just that its kind of a dead format, and they have several known quirks.  The only thing I could think of would be some kind of JavaScript to Excel integration.  Is that what you're doing? Or is there some other reason you like OADates?

**Comment by markhealey** [comment]
@mj1856, our database dates are stored as OADates. There are plenty of dependencies within our global infrastructure on this format and being able to pass around a number proved far simpler years ago when this was implemented. Having utilities—such as this plugin—to get from OADate to another format is important. We have a collection of javascript libs and most of the code in this plugin was sourced from those libraries. Admittedly, we rely on C# .NET to handle a lot of date translation (which has its own issues, [as you know](http://momentjs.com/docs/#/parsing/asp-net-json-date/)) before data gets to the browser but not always.

**Comment by mattjohnsonpint** [comment]
Ok, I can understand that.  Just be cautious of how they are used. My concerns would be 1) time zone basis, and 2) floating point rounding errors.

There's a big push lately to migrate towards ISO8601 dates on the wire and on the web.  You may find in time that it is more practical to convert from OADate to DateTime in .net and push ISO8601 strings out from there.

The floating point errors might be catching you already, since `DateTime.ToOADate` and `DateTime.FromOADate` use `double` instead of `decimal` types.  But perhaps the error is too small in precision to be noticeable.

Also, most databases that I know of have native date and time types, so you could always tackle it from that perspective.

But I respect your decision if you choose to move forward with this plugin.  I'd just want to make sure it has properly implemented all of the design quirks of the OADate format.

**Comment by markhealey** [comment]
Thanks @mj1856. We've been using this JS code for years and while there might be some quirks in the implementation, any errors are indeed too small to be noticeable.

**Comment by brianbaker** [comment]
I believe everything was covered in this old thread...  if not we can reopen new issues.
