### ISSUE TITLE
not on npm?

### ISSUE THREAD

**Issue by brianbaker** [markitondemand/moment-msdate#2]
This plugin should be installable via `npm install moment-msdate` like all other plugins...

**Comment by zackferraro** [comment]
Or at least include a package json so we can specify the git repo as the dependency path.

**Comment by teohhanhui** [comment]
So it this version `1.0` as seen on the `Releases` page or `0.1.0` as stated in `package.json`?

**Comment by brianbaker** [comment]
Looks like way back then there wasn't a package.json or anything.  I'll take a look at redoing that release and also creating another newer one so that it aligns to the package.json.  `npm install moment-msdate` will get you the latest code regardless.
